name: kycravings
description: "Know Your Cravings App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.6
  drift: ^2.19.1+1
  drift_flutter: ^0.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  injectable: ^2.4.4
  intl: ^0.19.0
  lottie: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  copy_with_extension_gen: ^5.0.4
  drift_dev: ^2.19.1
  fake_async: ^1.3.1
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/

flutter_intl:
  enabled: true
  class_name: I18n
  arb_dir: lib/presentation/shared/localization
  output_dir: lib/presentation/shared/localization/generated

flutter_gen:
  output: lib/presentation/shared/assets/
  line_length: 120
  fonts:
    enabled: false