name: kycravings
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  lottie: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/

flutter_intl:
  enabled: true
  class_name: I18n
  arb_dir: lib/presentation/shared/localization
  output_dir: lib/presentation/shared/localization/generated

flutter_gen:
  output: lib/presentation/shared/assets/
  line_length: 120
  fonts:
    enabled: false